export const queryKeys = {
  landing: ["landing"] as const,
  dashboard: ["dashboard"] as const,
  settings: ["settings"] as const,
  company: ["company"] as const,
  sms: (params?: unknown) => ["sms", params] as const,
  campaigns: (params?: unknown) => ["campaigns", params] as const,
  campaign: (id: string) => ["campaign", id] as const,
  analytics: ["analytics"] as const,
  analyticsBreakdown: ["analytics", "breakdown"] as const,
  nova: ["nova"] as const,
  novaHistory: ["nova", "history"] as const,
  billing: {
    plans: ["billing", "plans"] as const,
    pricing: ["billing", "pricing"] as const,
    promotions: ["billing", "promotions"] as const,
  },
  support: ["support"] as const,
  contacts: (params?: unknown) => ["contacts", params] as const,
  contact: (id: string) => ["contact", id] as const,
  crm: {
    deals: ["crm", "deals"] as const,
    activities: (id: string) => ["crm", "activities", id] as const,
  },
  notifications: ["notifications"] as const,
  notificationsUnread: ["notifications", "unread"] as const,
  recharges: ["recharges"] as const,
  rechargePackages: ["recharges", "packages"] as const,
  balance: ["balance"] as const,
  invoices: ["invoices"] as const,
  invoice: (id: string) => ["invoice", id] as const,
  apiKeys: ["api-keys"] as const,
  webhooks: ["webhooks"] as const,
  apiLogs: ["api-logs"] as const,
  users: ["users"] as const,
  currentUser: ["users", "current"] as const,
};
