/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AuthSessionExpiredRouteImport } from './routes/_auth.session-expired'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthAccountLockedRouteImport } from './routes/_auth.account-locked'
import { Route as AppSoporteRouteImport } from './routes/_app.soporte'
import { Route as AppNovaRouteImport } from './routes/_app.nova'
import { Route as AppMiEmpresaRouteImport } from './routes/_app.mi-empresa'
import { Route as AppFinanzasRouteImport } from './routes/_app.finanzas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'
import { Route as AppComunicacionRouteImport } from './routes/_app.comunicacion'
import { Route as AppCentroDeContactosRouteImport } from './routes/_app.centro-de-contactos'
import { Route as AppAutomatizacionesRouteImport } from './routes/_app.automatizaciones'
import { Route as AppApiRouteImport } from './routes/_app.api'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicSmsSchedulerRouteImport } from './routes/api/public/sms-scheduler'
import { Route as AppNovaMapasRouteImport } from './routes/_app.nova.mapas'
import { Route as AppCrmLegacyRouteImport } from './routes/_app.crm.legacy'
import { Route as AdminAdminWhatsappInventoryRouteImport } from './routes/_admin.admin.whatsapp-inventory'
import { Route as AdminAdminWalletRouteImport } from './routes/_admin.admin.wallet'
import { Route as AdminAdminUsuariosRouteImport } from './routes/_admin.admin.usuarios'
import { Route as AdminAdminTarifasRouteImport } from './routes/_admin.admin.tarifas'
import { Route as AdminAdminSistemaRouteImport } from './routes/_admin.admin.sistema'
import { Route as AdminAdminSeguridadRouteImport } from './routes/_admin.admin.seguridad'
import { Route as AdminAdminRolesRouteImport } from './routes/_admin.admin.roles'
import { Route as AdminAdminRecargasRouteImport } from './routes/_admin.admin.recargas'
import { Route as AdminAdminPromocionesRouteImport } from './routes/_admin.admin.promociones'
import { Route as AdminAdminPlanesRouteImport } from './routes/_admin.admin.planes'
import { Route as AdminAdminPermisosRouteImport } from './routes/_admin.admin.permisos'
import { Route as AdminAdminPagosRouteImport } from './routes/_admin.admin.pagos'
import { Route as AdminAdminNotificacionesRouteImport } from './routes/_admin.admin.notificaciones'
import { Route as AdminAdminLogsRouteImport } from './routes/_admin.admin.logs'
import { Route as AdminAdminLandingCmsRouteImport } from './routes/_admin.admin.landing-cms'
import { Route as AdminAdminIntegracionesRouteImport } from './routes/_admin.admin.integraciones'
import { Route as AdminAdminHistorialComercialRouteImport } from './routes/_admin.admin.historial-comercial'
import { Route as AdminAdminFeatureFlagsRouteImport } from './routes/_admin.admin.feature-flags'
import { Route as AdminAdminEmpresasRouteImport } from './routes/_admin.admin.empresas'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminConfigWhatsappRouteImport } from './routes/_admin.admin.config-whatsapp'
import { Route as AdminAdminConfigSmsRouteImport } from './routes/_admin.admin.config-sms'
import { Route as AdminAdminConfigNovaRouteImport } from './routes/_admin.admin.config-nova'
import { Route as AdminAdminConfigGeneralRouteImport } from './routes/_admin.admin.config-general'
import { Route as AdminAdminConfigApiRouteImport } from './routes/_admin.admin.config-api'
import { Route as AdminAdminCommunicationRouteImport } from './routes/_admin.admin.communication'
import { Route as AdminAdminAuditoriaRouteImport } from './routes/_admin.admin.auditoria'
import { Route as ApiPublicWebhooksWompiRouteImport } from './routes/api/public/webhooks/wompi'
import { Route as AppComunicacionWhatsappContactosRouteImport } from './routes/_app.comunicacion.whatsapp.contactos'
import { Route as AdminAdminEmpresasCompanyIdWhatsappRouteImport } from './routes/_admin.admin.empresas.$companyId.whatsapp'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSessionExpiredRoute = AuthSessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountLockedRoute = AuthAccountLockedRouteImport.update({
  id: '/account-locked',
  path: '/account-locked',
  getParentRoute: () => AuthRoute,
} as any)
const AppSoporteRoute = AppSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaRoute = AppNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppMiEmpresaRoute = AppMiEmpresaRouteImport.update({
  id: '/mi-empresa',
  path: '/mi-empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacionRoute = AppComunicacionRouteImport.update({
  id: '/comunicacion',
  path: '/comunicacion',
  getParentRoute: () => AppRoute,
} as any)
const AppCentroDeContactosRoute = AppCentroDeContactosRouteImport.update({
  id: '/centro-de-contactos',
  path: '/centro-de-contactos',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomatizacionesRoute = AppAutomatizacionesRouteImport.update({
  id: '/automatizaciones',
  path: '/automatizaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSmsSchedulerRoute = ApiPublicSmsSchedulerRouteImport.update({
  id: '/api/public/sms-scheduler',
  path: '/api/public/sms-scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNovaMapasRoute = AppNovaMapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => AppNovaRoute,
} as any)
const AppCrmLegacyRoute = AppCrmLegacyRouteImport.update({
  id: '/crm/legacy',
  path: '/crm/legacy',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminWhatsappInventoryRoute =
  AdminAdminWhatsappInventoryRouteImport.update({
    id: '/admin/whatsapp-inventory',
    path: '/admin/whatsapp-inventory',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminWalletRoute = AdminAdminWalletRouteImport.update({
  id: '/admin/wallet',
  path: '/admin/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsuariosRoute = AdminAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTarifasRoute = AdminAdminTarifasRouteImport.update({
  id: '/admin/tarifas',
  path: '/admin/tarifas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSistemaRoute = AdminAdminSistemaRouteImport.update({
  id: '/admin/sistema',
  path: '/admin/sistema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSeguridadRoute = AdminAdminSeguridadRouteImport.update({
  id: '/admin/seguridad',
  path: '/admin/seguridad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRolesRoute = AdminAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRecargasRoute = AdminAdminRecargasRouteImport.update({
  id: '/admin/recargas',
  path: '/admin/recargas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPromocionesRoute = AdminAdminPromocionesRouteImport.update({
  id: '/admin/promociones',
  path: '/admin/promociones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPlanesRoute = AdminAdminPlanesRouteImport.update({
  id: '/admin/planes',
  path: '/admin/planes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPermisosRoute = AdminAdminPermisosRouteImport.update({
  id: '/admin/permisos',
  path: '/admin/permisos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPagosRoute = AdminAdminPagosRouteImport.update({
  id: '/admin/pagos',
  path: '/admin/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificacionesRoute =
  AdminAdminNotificacionesRouteImport.update({
    id: '/admin/notificaciones',
    path: '/admin/notificaciones',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminLogsRoute = AdminAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLandingCmsRoute = AdminAdminLandingCmsRouteImport.update({
  id: '/admin/landing-cms',
  path: '/admin/landing-cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIntegracionesRoute = AdminAdminIntegracionesRouteImport.update({
  id: '/admin/integraciones',
  path: '/admin/integraciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminHistorialComercialRoute =
  AdminAdminHistorialComercialRouteImport.update({
    id: '/admin/historial-comercial',
    path: '/admin/historial-comercial',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminFeatureFlagsRoute = AdminAdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEmpresasRoute = AdminAdminEmpresasRouteImport.update({
  id: '/admin/empresas',
  path: '/admin/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConfigWhatsappRoute =
  AdminAdminConfigWhatsappRouteImport.update({
    id: '/admin/config-whatsapp',
    path: '/admin/config-whatsapp',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminConfigSmsRoute = AdminAdminConfigSmsRouteImport.update({
  id: '/admin/config-sms',
  path: '/admin/config-sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConfigNovaRoute = AdminAdminConfigNovaRouteImport.update({
  id: '/admin/config-nova',
  path: '/admin/config-nova',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConfigGeneralRoute = AdminAdminConfigGeneralRouteImport.update({
  id: '/admin/config-general',
  path: '/admin/config-general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConfigApiRoute = AdminAdminConfigApiRouteImport.update({
  id: '/admin/config-api',
  path: '/admin/config-api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCommunicationRoute = AdminAdminCommunicationRouteImport.update({
  id: '/admin/communication',
  path: '/admin/communication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuditoriaRoute = AdminAdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWebhooksWompiRoute = ApiPublicWebhooksWompiRouteImport.update({
  id: '/api/public/webhooks/wompi',
  path: '/api/public/webhooks/wompi',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComunicacionWhatsappContactosRoute =
  AppComunicacionWhatsappContactosRouteImport.update({
    id: '/whatsapp/contactos',
    path: '/whatsapp/contactos',
    getParentRoute: () => AppComunicacionRoute,
  } as any)
const AdminAdminEmpresasCompanyIdWhatsappRoute =
  AdminAdminEmpresasCompanyIdWhatsappRouteImport.update({
    id: '/$companyId/whatsapp',
    path: '/$companyId/whatsapp',
    getParentRoute: () => AdminAdminEmpresasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api': typeof AppApiRoute
  '/automatizaciones': typeof AppAutomatizacionesRoute
  '/centro-de-contactos': typeof AppCentroDeContactosRoute
  '/comunicacion': typeof AppComunicacionRouteWithChildren
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/finanzas': typeof AppFinanzasRoute
  '/mi-empresa': typeof AppMiEmpresaRoute
  '/nova': typeof AppNovaRouteWithChildren
  '/soporte': typeof AppSoporteRoute
  '/account-locked': typeof AuthAccountLockedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/session-expired': typeof AuthSessionExpiredRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/communication': typeof AdminAdminCommunicationRoute
  '/admin/config-api': typeof AdminAdminConfigApiRoute
  '/admin/config-general': typeof AdminAdminConfigGeneralRoute
  '/admin/config-nova': typeof AdminAdminConfigNovaRoute
  '/admin/config-sms': typeof AdminAdminConfigSmsRoute
  '/admin/config-whatsapp': typeof AdminAdminConfigWhatsappRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/empresas': typeof AdminAdminEmpresasRouteWithChildren
  '/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/admin/historial-comercial': typeof AdminAdminHistorialComercialRoute
  '/admin/integraciones': typeof AdminAdminIntegracionesRoute
  '/admin/landing-cms': typeof AdminAdminLandingCmsRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/notificaciones': typeof AdminAdminNotificacionesRoute
  '/admin/pagos': typeof AdminAdminPagosRoute
  '/admin/permisos': typeof AdminAdminPermisosRoute
  '/admin/planes': typeof AdminAdminPlanesRoute
  '/admin/promociones': typeof AdminAdminPromocionesRoute
  '/admin/recargas': typeof AdminAdminRecargasRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/seguridad': typeof AdminAdminSeguridadRoute
  '/admin/sistema': typeof AdminAdminSistemaRoute
  '/admin/tarifas': typeof AdminAdminTarifasRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/admin/wallet': typeof AdminAdminWalletRoute
  '/admin/whatsapp-inventory': typeof AdminAdminWhatsappInventoryRoute
  '/crm/legacy': typeof AppCrmLegacyRoute
  '/nova/mapas': typeof AppNovaMapasRoute
  '/api/public/sms-scheduler': typeof ApiPublicSmsSchedulerRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/comunicacion/whatsapp/contactos': typeof AppComunicacionWhatsappContactosRoute
  '/api/public/webhooks/wompi': typeof ApiPublicWebhooksWompiRoute
  '/admin/empresas/$companyId/whatsapp': typeof AdminAdminEmpresasCompanyIdWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api': typeof AppApiRoute
  '/automatizaciones': typeof AppAutomatizacionesRoute
  '/centro-de-contactos': typeof AppCentroDeContactosRoute
  '/comunicacion': typeof AppComunicacionRouteWithChildren
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/finanzas': typeof AppFinanzasRoute
  '/mi-empresa': typeof AppMiEmpresaRoute
  '/nova': typeof AppNovaRouteWithChildren
  '/soporte': typeof AppSoporteRoute
  '/account-locked': typeof AuthAccountLockedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/session-expired': typeof AuthSessionExpiredRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/communication': typeof AdminAdminCommunicationRoute
  '/admin/config-api': typeof AdminAdminConfigApiRoute
  '/admin/config-general': typeof AdminAdminConfigGeneralRoute
  '/admin/config-nova': typeof AdminAdminConfigNovaRoute
  '/admin/config-sms': typeof AdminAdminConfigSmsRoute
  '/admin/config-whatsapp': typeof AdminAdminConfigWhatsappRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/empresas': typeof AdminAdminEmpresasRouteWithChildren
  '/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/admin/historial-comercial': typeof AdminAdminHistorialComercialRoute
  '/admin/integraciones': typeof AdminAdminIntegracionesRoute
  '/admin/landing-cms': typeof AdminAdminLandingCmsRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/notificaciones': typeof AdminAdminNotificacionesRoute
  '/admin/pagos': typeof AdminAdminPagosRoute
  '/admin/permisos': typeof AdminAdminPermisosRoute
  '/admin/planes': typeof AdminAdminPlanesRoute
  '/admin/promociones': typeof AdminAdminPromocionesRoute
  '/admin/recargas': typeof AdminAdminRecargasRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/seguridad': typeof AdminAdminSeguridadRoute
  '/admin/sistema': typeof AdminAdminSistemaRoute
  '/admin/tarifas': typeof AdminAdminTarifasRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/admin/wallet': typeof AdminAdminWalletRoute
  '/admin/whatsapp-inventory': typeof AdminAdminWhatsappInventoryRoute
  '/crm/legacy': typeof AppCrmLegacyRoute
  '/nova/mapas': typeof AppNovaMapasRoute
  '/api/public/sms-scheduler': typeof ApiPublicSmsSchedulerRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/comunicacion/whatsapp/contactos': typeof AppComunicacionWhatsappContactosRoute
  '/api/public/webhooks/wompi': typeof ApiPublicWebhooksWompiRoute
  '/admin/empresas/$companyId/whatsapp': typeof AdminAdminEmpresasCompanyIdWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api': typeof AppApiRoute
  '/_app/automatizaciones': typeof AppAutomatizacionesRoute
  '/_app/centro-de-contactos': typeof AppCentroDeContactosRoute
  '/_app/comunicacion': typeof AppComunicacionRouteWithChildren
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finanzas': typeof AppFinanzasRoute
  '/_app/mi-empresa': typeof AppMiEmpresaRoute
  '/_app/nova': typeof AppNovaRouteWithChildren
  '/_app/soporte': typeof AppSoporteRoute
  '/_auth/account-locked': typeof AuthAccountLockedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/session-expired': typeof AuthSessionExpiredRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_admin/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/_admin/admin/communication': typeof AdminAdminCommunicationRoute
  '/_admin/admin/config-api': typeof AdminAdminConfigApiRoute
  '/_admin/admin/config-general': typeof AdminAdminConfigGeneralRoute
  '/_admin/admin/config-nova': typeof AdminAdminConfigNovaRoute
  '/_admin/admin/config-sms': typeof AdminAdminConfigSmsRoute
  '/_admin/admin/config-whatsapp': typeof AdminAdminConfigWhatsappRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/empresas': typeof AdminAdminEmpresasRouteWithChildren
  '/_admin/admin/feature-flags': typeof AdminAdminFeatureFlagsRoute
  '/_admin/admin/historial-comercial': typeof AdminAdminHistorialComercialRoute
  '/_admin/admin/integraciones': typeof AdminAdminIntegracionesRoute
  '/_admin/admin/landing-cms': typeof AdminAdminLandingCmsRoute
  '/_admin/admin/logs': typeof AdminAdminLogsRoute
  '/_admin/admin/notificaciones': typeof AdminAdminNotificacionesRoute
  '/_admin/admin/pagos': typeof AdminAdminPagosRoute
  '/_admin/admin/permisos': typeof AdminAdminPermisosRoute
  '/_admin/admin/planes': typeof AdminAdminPlanesRoute
  '/_admin/admin/promociones': typeof AdminAdminPromocionesRoute
  '/_admin/admin/recargas': typeof AdminAdminRecargasRoute
  '/_admin/admin/roles': typeof AdminAdminRolesRoute
  '/_admin/admin/seguridad': typeof AdminAdminSeguridadRoute
  '/_admin/admin/sistema': typeof AdminAdminSistemaRoute
  '/_admin/admin/tarifas': typeof AdminAdminTarifasRoute
  '/_admin/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/_admin/admin/wallet': typeof AdminAdminWalletRoute
  '/_admin/admin/whatsapp-inventory': typeof AdminAdminWhatsappInventoryRoute
  '/_app/crm/legacy': typeof AppCrmLegacyRoute
  '/_app/nova/mapas': typeof AppNovaMapasRoute
  '/api/public/sms-scheduler': typeof ApiPublicSmsSchedulerRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/_app/comunicacion/whatsapp/contactos': typeof AppComunicacionWhatsappContactosRoute
  '/api/public/webhooks/wompi': typeof ApiPublicWebhooksWompiRoute
  '/_admin/admin/empresas/$companyId/whatsapp': typeof AdminAdminEmpresasCompanyIdWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api'
    | '/automatizaciones'
    | '/centro-de-contactos'
    | '/comunicacion'
    | '/configuracion'
    | '/dashboard'
    | '/finanzas'
    | '/mi-empresa'
    | '/nova'
    | '/soporte'
    | '/account-locked'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/verify-email'
    | '/admin/auditoria'
    | '/admin/communication'
    | '/admin/config-api'
    | '/admin/config-general'
    | '/admin/config-nova'
    | '/admin/config-sms'
    | '/admin/config-whatsapp'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/feature-flags'
    | '/admin/historial-comercial'
    | '/admin/integraciones'
    | '/admin/landing-cms'
    | '/admin/logs'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/admin/permisos'
    | '/admin/planes'
    | '/admin/promociones'
    | '/admin/recargas'
    | '/admin/roles'
    | '/admin/seguridad'
    | '/admin/sistema'
    | '/admin/tarifas'
    | '/admin/usuarios'
    | '/admin/wallet'
    | '/admin/whatsapp-inventory'
    | '/crm/legacy'
    | '/nova/mapas'
    | '/api/public/sms-scheduler'
    | '/api/public/whatsapp-webhook'
    | '/comunicacion/whatsapp/contactos'
    | '/api/public/webhooks/wompi'
    | '/admin/empresas/$companyId/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api'
    | '/automatizaciones'
    | '/centro-de-contactos'
    | '/comunicacion'
    | '/configuracion'
    | '/dashboard'
    | '/finanzas'
    | '/mi-empresa'
    | '/nova'
    | '/soporte'
    | '/account-locked'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/verify-email'
    | '/admin/auditoria'
    | '/admin/communication'
    | '/admin/config-api'
    | '/admin/config-general'
    | '/admin/config-nova'
    | '/admin/config-sms'
    | '/admin/config-whatsapp'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/feature-flags'
    | '/admin/historial-comercial'
    | '/admin/integraciones'
    | '/admin/landing-cms'
    | '/admin/logs'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/admin/permisos'
    | '/admin/planes'
    | '/admin/promociones'
    | '/admin/recargas'
    | '/admin/roles'
    | '/admin/seguridad'
    | '/admin/sistema'
    | '/admin/tarifas'
    | '/admin/usuarios'
    | '/admin/wallet'
    | '/admin/whatsapp-inventory'
    | '/crm/legacy'
    | '/nova/mapas'
    | '/api/public/sms-scheduler'
    | '/api/public/whatsapp-webhook'
    | '/comunicacion/whatsapp/contactos'
    | '/api/public/webhooks/wompi'
    | '/admin/empresas/$companyId/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/_auth'
    | '/_app/analytics'
    | '/_app/api'
    | '/_app/automatizaciones'
    | '/_app/centro-de-contactos'
    | '/_app/comunicacion'
    | '/_app/configuracion'
    | '/_app/dashboard'
    | '/_app/finanzas'
    | '/_app/mi-empresa'
    | '/_app/nova'
    | '/_app/soporte'
    | '/_auth/account-locked'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/session-expired'
    | '/_auth/verify-email'
    | '/_admin/admin/auditoria'
    | '/_admin/admin/communication'
    | '/_admin/admin/config-api'
    | '/_admin/admin/config-general'
    | '/_admin/admin/config-nova'
    | '/_admin/admin/config-sms'
    | '/_admin/admin/config-whatsapp'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/empresas'
    | '/_admin/admin/feature-flags'
    | '/_admin/admin/historial-comercial'
    | '/_admin/admin/integraciones'
    | '/_admin/admin/landing-cms'
    | '/_admin/admin/logs'
    | '/_admin/admin/notificaciones'
    | '/_admin/admin/pagos'
    | '/_admin/admin/permisos'
    | '/_admin/admin/planes'
    | '/_admin/admin/promociones'
    | '/_admin/admin/recargas'
    | '/_admin/admin/roles'
    | '/_admin/admin/seguridad'
    | '/_admin/admin/sistema'
    | '/_admin/admin/tarifas'
    | '/_admin/admin/usuarios'
    | '/_admin/admin/wallet'
    | '/_admin/admin/whatsapp-inventory'
    | '/_app/crm/legacy'
    | '/_app/nova/mapas'
    | '/api/public/sms-scheduler'
    | '/api/public/whatsapp-webhook'
    | '/_app/comunicacion/whatsapp/contactos'
    | '/api/public/webhooks/wompi'
    | '/_admin/admin/empresas/$companyId/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicSmsSchedulerRoute: typeof ApiPublicSmsSchedulerRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicWebhooksWompiRoute: typeof ApiPublicWebhooksWompiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/session-expired': {
      id: '/_auth/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof AuthSessionExpiredRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account-locked': {
      id: '/_auth/account-locked'
      path: '/account-locked'
      fullPath: '/account-locked'
      preLoaderRoute: typeof AuthAccountLockedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/soporte': {
      id: '/_app/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof AppSoporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova': {
      id: '/_app/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AppNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mi-empresa': {
      id: '/_app/mi-empresa'
      path: '/mi-empresa'
      fullPath: '/mi-empresa'
      preLoaderRoute: typeof AppMiEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finanzas': {
      id: '/_app/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunicacion': {
      id: '/_app/comunicacion'
      path: '/comunicacion'
      fullPath: '/comunicacion'
      preLoaderRoute: typeof AppComunicacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/centro-de-contactos': {
      id: '/_app/centro-de-contactos'
      path: '/centro-de-contactos'
      fullPath: '/centro-de-contactos'
      preLoaderRoute: typeof AppCentroDeContactosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automatizaciones': {
      id: '/_app/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/automatizaciones'
      preLoaderRoute: typeof AppAutomatizacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api': {
      id: '/_app/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms-scheduler': {
      id: '/api/public/sms-scheduler'
      path: '/api/public/sms-scheduler'
      fullPath: '/api/public/sms-scheduler'
      preLoaderRoute: typeof ApiPublicSmsSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/nova/mapas': {
      id: '/_app/nova/mapas'
      path: '/mapas'
      fullPath: '/nova/mapas'
      preLoaderRoute: typeof AppNovaMapasRouteImport
      parentRoute: typeof AppNovaRoute
    }
    '/_app/crm/legacy': {
      id: '/_app/crm/legacy'
      path: '/crm/legacy'
      fullPath: '/crm/legacy'
      preLoaderRoute: typeof AppCrmLegacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/whatsapp-inventory': {
      id: '/_admin/admin/whatsapp-inventory'
      path: '/admin/whatsapp-inventory'
      fullPath: '/admin/whatsapp-inventory'
      preLoaderRoute: typeof AdminAdminWhatsappInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/wallet': {
      id: '/_admin/admin/wallet'
      path: '/admin/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminAdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/usuarios': {
      id: '/_admin/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminAdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/tarifas': {
      id: '/_admin/admin/tarifas'
      path: '/admin/tarifas'
      fullPath: '/admin/tarifas'
      preLoaderRoute: typeof AdminAdminTarifasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/sistema': {
      id: '/_admin/admin/sistema'
      path: '/admin/sistema'
      fullPath: '/admin/sistema'
      preLoaderRoute: typeof AdminAdminSistemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/seguridad': {
      id: '/_admin/admin/seguridad'
      path: '/admin/seguridad'
      fullPath: '/admin/seguridad'
      preLoaderRoute: typeof AdminAdminSeguridadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/roles': {
      id: '/_admin/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminAdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/recargas': {
      id: '/_admin/admin/recargas'
      path: '/admin/recargas'
      fullPath: '/admin/recargas'
      preLoaderRoute: typeof AdminAdminRecargasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/promociones': {
      id: '/_admin/admin/promociones'
      path: '/admin/promociones'
      fullPath: '/admin/promociones'
      preLoaderRoute: typeof AdminAdminPromocionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/planes': {
      id: '/_admin/admin/planes'
      path: '/admin/planes'
      fullPath: '/admin/planes'
      preLoaderRoute: typeof AdminAdminPlanesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/permisos': {
      id: '/_admin/admin/permisos'
      path: '/admin/permisos'
      fullPath: '/admin/permisos'
      preLoaderRoute: typeof AdminAdminPermisosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pagos': {
      id: '/_admin/admin/pagos'
      path: '/admin/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminAdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/notificaciones': {
      id: '/_admin/admin/notificaciones'
      path: '/admin/notificaciones'
      fullPath: '/admin/notificaciones'
      preLoaderRoute: typeof AdminAdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/logs': {
      id: '/_admin/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminAdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/landing-cms': {
      id: '/_admin/admin/landing-cms'
      path: '/admin/landing-cms'
      fullPath: '/admin/landing-cms'
      preLoaderRoute: typeof AdminAdminLandingCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/integraciones': {
      id: '/_admin/admin/integraciones'
      path: '/admin/integraciones'
      fullPath: '/admin/integraciones'
      preLoaderRoute: typeof AdminAdminIntegracionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/historial-comercial': {
      id: '/_admin/admin/historial-comercial'
      path: '/admin/historial-comercial'
      fullPath: '/admin/historial-comercial'
      preLoaderRoute: typeof AdminAdminHistorialComercialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/feature-flags': {
      id: '/_admin/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminAdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/empresas': {
      id: '/_admin/admin/empresas'
      path: '/admin/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminAdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/config-whatsapp': {
      id: '/_admin/admin/config-whatsapp'
      path: '/admin/config-whatsapp'
      fullPath: '/admin/config-whatsapp'
      preLoaderRoute: typeof AdminAdminConfigWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/config-sms': {
      id: '/_admin/admin/config-sms'
      path: '/admin/config-sms'
      fullPath: '/admin/config-sms'
      preLoaderRoute: typeof AdminAdminConfigSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/config-nova': {
      id: '/_admin/admin/config-nova'
      path: '/admin/config-nova'
      fullPath: '/admin/config-nova'
      preLoaderRoute: typeof AdminAdminConfigNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/config-general': {
      id: '/_admin/admin/config-general'
      path: '/admin/config-general'
      fullPath: '/admin/config-general'
      preLoaderRoute: typeof AdminAdminConfigGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/config-api': {
      id: '/_admin/admin/config-api'
      path: '/admin/config-api'
      fullPath: '/admin/config-api'
      preLoaderRoute: typeof AdminAdminConfigApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/communication': {
      id: '/_admin/admin/communication'
      path: '/admin/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminAdminCommunicationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/auditoria': {
      id: '/_admin/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/webhooks/wompi': {
      id: '/api/public/webhooks/wompi'
      path: '/api/public/webhooks/wompi'
      fullPath: '/api/public/webhooks/wompi'
      preLoaderRoute: typeof ApiPublicWebhooksWompiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/comunicacion/whatsapp/contactos': {
      id: '/_app/comunicacion/whatsapp/contactos'
      path: '/whatsapp/contactos'
      fullPath: '/comunicacion/whatsapp/contactos'
      preLoaderRoute: typeof AppComunicacionWhatsappContactosRouteImport
      parentRoute: typeof AppComunicacionRoute
    }
    '/_admin/admin/empresas/$companyId/whatsapp': {
      id: '/_admin/admin/empresas/$companyId/whatsapp'
      path: '/$companyId/whatsapp'
      fullPath: '/admin/empresas/$companyId/whatsapp'
      preLoaderRoute: typeof AdminAdminEmpresasCompanyIdWhatsappRouteImport
      parentRoute: typeof AdminAdminEmpresasRoute
    }
  }
}

interface AdminAdminEmpresasRouteChildren {
  AdminAdminEmpresasCompanyIdWhatsappRoute: typeof AdminAdminEmpresasCompanyIdWhatsappRoute
}

const AdminAdminEmpresasRouteChildren: AdminAdminEmpresasRouteChildren = {
  AdminAdminEmpresasCompanyIdWhatsappRoute:
    AdminAdminEmpresasCompanyIdWhatsappRoute,
}

const AdminAdminEmpresasRouteWithChildren =
  AdminAdminEmpresasRoute._addFileChildren(AdminAdminEmpresasRouteChildren)

interface AdminRouteChildren {
  AdminAdminAuditoriaRoute: typeof AdminAdminAuditoriaRoute
  AdminAdminCommunicationRoute: typeof AdminAdminCommunicationRoute
  AdminAdminConfigApiRoute: typeof AdminAdminConfigApiRoute
  AdminAdminConfigGeneralRoute: typeof AdminAdminConfigGeneralRoute
  AdminAdminConfigNovaRoute: typeof AdminAdminConfigNovaRoute
  AdminAdminConfigSmsRoute: typeof AdminAdminConfigSmsRoute
  AdminAdminConfigWhatsappRoute: typeof AdminAdminConfigWhatsappRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminEmpresasRoute: typeof AdminAdminEmpresasRouteWithChildren
  AdminAdminFeatureFlagsRoute: typeof AdminAdminFeatureFlagsRoute
  AdminAdminHistorialComercialRoute: typeof AdminAdminHistorialComercialRoute
  AdminAdminIntegracionesRoute: typeof AdminAdminIntegracionesRoute
  AdminAdminLandingCmsRoute: typeof AdminAdminLandingCmsRoute
  AdminAdminLogsRoute: typeof AdminAdminLogsRoute
  AdminAdminNotificacionesRoute: typeof AdminAdminNotificacionesRoute
  AdminAdminPagosRoute: typeof AdminAdminPagosRoute
  AdminAdminPermisosRoute: typeof AdminAdminPermisosRoute
  AdminAdminPlanesRoute: typeof AdminAdminPlanesRoute
  AdminAdminPromocionesRoute: typeof AdminAdminPromocionesRoute
  AdminAdminRecargasRoute: typeof AdminAdminRecargasRoute
  AdminAdminRolesRoute: typeof AdminAdminRolesRoute
  AdminAdminSeguridadRoute: typeof AdminAdminSeguridadRoute
  AdminAdminSistemaRoute: typeof AdminAdminSistemaRoute
  AdminAdminTarifasRoute: typeof AdminAdminTarifasRoute
  AdminAdminUsuariosRoute: typeof AdminAdminUsuariosRoute
  AdminAdminWalletRoute: typeof AdminAdminWalletRoute
  AdminAdminWhatsappInventoryRoute: typeof AdminAdminWhatsappInventoryRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAuditoriaRoute: AdminAdminAuditoriaRoute,
  AdminAdminCommunicationRoute: AdminAdminCommunicationRoute,
  AdminAdminConfigApiRoute: AdminAdminConfigApiRoute,
  AdminAdminConfigGeneralRoute: AdminAdminConfigGeneralRoute,
  AdminAdminConfigNovaRoute: AdminAdminConfigNovaRoute,
  AdminAdminConfigSmsRoute: AdminAdminConfigSmsRoute,
  AdminAdminConfigWhatsappRoute: AdminAdminConfigWhatsappRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminEmpresasRoute: AdminAdminEmpresasRouteWithChildren,
  AdminAdminFeatureFlagsRoute: AdminAdminFeatureFlagsRoute,
  AdminAdminHistorialComercialRoute: AdminAdminHistorialComercialRoute,
  AdminAdminIntegracionesRoute: AdminAdminIntegracionesRoute,
  AdminAdminLandingCmsRoute: AdminAdminLandingCmsRoute,
  AdminAdminLogsRoute: AdminAdminLogsRoute,
  AdminAdminNotificacionesRoute: AdminAdminNotificacionesRoute,
  AdminAdminPagosRoute: AdminAdminPagosRoute,
  AdminAdminPermisosRoute: AdminAdminPermisosRoute,
  AdminAdminPlanesRoute: AdminAdminPlanesRoute,
  AdminAdminPromocionesRoute: AdminAdminPromocionesRoute,
  AdminAdminRecargasRoute: AdminAdminRecargasRoute,
  AdminAdminRolesRoute: AdminAdminRolesRoute,
  AdminAdminSeguridadRoute: AdminAdminSeguridadRoute,
  AdminAdminSistemaRoute: AdminAdminSistemaRoute,
  AdminAdminTarifasRoute: AdminAdminTarifasRoute,
  AdminAdminUsuariosRoute: AdminAdminUsuariosRoute,
  AdminAdminWalletRoute: AdminAdminWalletRoute,
  AdminAdminWhatsappInventoryRoute: AdminAdminWhatsappInventoryRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppComunicacionRouteChildren {
  AppComunicacionWhatsappContactosRoute: typeof AppComunicacionWhatsappContactosRoute
}

const AppComunicacionRouteChildren: AppComunicacionRouteChildren = {
  AppComunicacionWhatsappContactosRoute: AppComunicacionWhatsappContactosRoute,
}

const AppComunicacionRouteWithChildren = AppComunicacionRoute._addFileChildren(
  AppComunicacionRouteChildren,
)

interface AppNovaRouteChildren {
  AppNovaMapasRoute: typeof AppNovaMapasRoute
}

const AppNovaRouteChildren: AppNovaRouteChildren = {
  AppNovaMapasRoute: AppNovaMapasRoute,
}

const AppNovaRouteWithChildren =
  AppNovaRoute._addFileChildren(AppNovaRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiRoute: typeof AppApiRoute
  AppAutomatizacionesRoute: typeof AppAutomatizacionesRoute
  AppCentroDeContactosRoute: typeof AppCentroDeContactosRoute
  AppComunicacionRoute: typeof AppComunicacionRouteWithChildren
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppMiEmpresaRoute: typeof AppMiEmpresaRoute
  AppNovaRoute: typeof AppNovaRouteWithChildren
  AppSoporteRoute: typeof AppSoporteRoute
  AppCrmLegacyRoute: typeof AppCrmLegacyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiRoute: AppApiRoute,
  AppAutomatizacionesRoute: AppAutomatizacionesRoute,
  AppCentroDeContactosRoute: AppCentroDeContactosRoute,
  AppComunicacionRoute: AppComunicacionRouteWithChildren,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanzasRoute: AppFinanzasRoute,
  AppMiEmpresaRoute: AppMiEmpresaRoute,
  AppNovaRoute: AppNovaRouteWithChildren,
  AppSoporteRoute: AppSoporteRoute,
  AppCrmLegacyRoute: AppCrmLegacyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthAccountLockedRoute: typeof AuthAccountLockedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSessionExpiredRoute: typeof AuthSessionExpiredRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountLockedRoute: AuthAccountLockedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSessionExpiredRoute: AuthSessionExpiredRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicSmsSchedulerRoute: ApiPublicSmsSchedulerRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicWebhooksWompiRoute: ApiPublicWebhooksWompiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
